# Generated by Django 2.2.6 on 2020-01-06 10:20

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('via', multiselectfield.db.fields.MultiSelectField(choices=[('email', 'Email'), ('push_notification', 'Push Notification'), ('sms', 'SMS')], max_length=27)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
