# Generated by Django 2.2.6 on 2020-01-08 04:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='content',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='html_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Kontek untuk siaran via Email', null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='short_content',
            field=models.TextField(blank=True, help_text='Kontek untuk siaran via Push Notification dan SMS', max_length=140, null=True),
        ),
    ]
