# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_trainingstatus'),
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
