# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_graduate_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='images/certificates/%Y/%m/%d'),
        ),
    ]
