# Generated by Django 2.1.7 on 2019-07-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0004_auto_20190629_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='channeled_at',
            field=models.CharField(default='', max_length=200),
        ),
    ]
