# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_trainingstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTrainingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Not Yet'), (2, 'Graduate'), (3, 'Repeat')], null=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_training_status', to='students.Student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_training_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
