# Generated by Django 2.1.7 on 2019-07-09 08:36

import academy.apps.logs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtrainingstatus',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(academy.apps.logs.models.get_sentinel_user), related_name='log_training_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
