# Generated by Django 2.1.4 on 2019-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/partners')),
                ('display_order', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('website', models.URLField(max_length=255)),
            ],
        ),
    ]
