# Generated by Django 2.2.6 on 2020-01-20 07:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_bannerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerinfo',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Tuliskan informasi yang akan ditampilkan.'),
        ),
    ]
