# Generated by Django 2.2.6 on 2020-01-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_auto_20200120_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerinfo',
            name='color_style',
            field=models.CharField(choices=[('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('primary', 'Primary'), ('info', 'Info')], default='success', max_length=50),
        ),
    ]
