# Generated by Django 2.2.10 on 2020-04-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0008_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='color_theme',
            field=models.PositiveIntegerField(choices=[(1, 'danger'), (2, 'warning'), (3, 'primary'), (4, 'success'), (5, 'dark')], default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sidebar_color',
            field=models.PositiveIntegerField(choices=[(1, 'light'), (2, 'dark')], default=1),
        ),
    ]
