# Generated by Django 2.2.10 on 2020-04-06 04:53

from django.db import migrations, models
from academy.apps.offices.models import Setting


def initial_apperance(apps, schema_editor):
    # initial apperance setting data
    Setting.objects.update_or_create(
        name="Apperance",
        defaults={
            'site_name': 'NolSatu',
            'footer_title': 'PT. Boer Technology (Btech)',
            'footer_url': 'https://btech.id/',
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0008_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images/settings'),
        ),
        migrations.RunPython(initial_apperance),
    ]
