# Generated by Django 2.2.10 on 2020-04-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0009_auto_20200402_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='footer_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
