# Generated by Django 2.2.10 on 2020-04-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0009_setting_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=255, verbose_name='Default From Email')),
                ('email_host', models.CharField(max_length=255, verbose_name='Email Host')),
                ('email_user', models.CharField(max_length=255, verbose_name='Email Host User')),
                ('email_password', models.CharField(max_length=255, verbose_name='Email Host Password')),
                ('email_port', models.IntegerField(verbose_name='Email Port')),
                ('use_tls', models.BooleanField(verbose_name='Email Use TLS')),
                ('recipient_email', models.EmailField(max_length=255, verbose_name='Default Recipient Email')),
            ],
        ),
    ]
