# Generated by Django 2.2.10 on 2020-04-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0010_configemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='hide_site_name',
            field=models.BooleanField(default=False, help_text='Menyumbunyikan site name pada Nav bar'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_name',
            field=models.CharField(help_text='Menyumbunyikan logo pada Nav bar', max_length=50),
        ),
    ]
