# Generated by Django 2.2.10 on 2020-04-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0010_setting_footer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='hide_logo',
            field=models.BooleanField(default=False),
        ),
    ]
