# Generated by Django 2.2.10 on 2020-06-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0011_auto_20200430_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Authorization', max_length=50)),
                ('sign_with_btech', models.BooleanField(default=True, verbose_name='Signin with Btech Account')),
            ],
        ),
    ]
