# Generated by Django 2.2.10 on 2020-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0013_setting_site_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='short_content',
            field=models.TextField(verbose_name='Konten Singkat'),
        ),
    ]
