# Generated by Django 2.2.10 on 2020-09-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0015_auto_20200911_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hidden_image',
            field=models.BooleanField(default=False, help_text='Sembunyikan gambar pada halaman detial', verbose_name='Sembunyikan gambar'),
        ),
    ]
