# Generated by Django 2.2.10 on 2020-09-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0018_auto_20200923_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type_content',
            field=models.PositiveIntegerField(choices=[(1, 'Halaman'), (2, 'Pos')], default=2),
        ),
    ]
