# Generated by Django 2.2.10 on 2020-09-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0018_auto_20200922_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
