# Generated by Django 2.2.10 on 2020-09-22 09:43

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('offices', '0019_auto_20200922_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='catpage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='offices.CategoryPage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='slug',
            field=models.SlugField(blank=True, help_text='Generate otomatis jika dikosongkan', unique=True),
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=taggit.managers.TaggableManager(help_text='Kategori dipisahkan dengan koma', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Kategori'),
        ),
    ]
