# Generated by Django 2.2.10 on 2020-09-23 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0020_auto_20200922_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='catpage',
        ),
        migrations.AddField(
            model_name='page',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='offices.CategoryPage'),
            preserve_default=False,
        ),
    ]
