# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_trainingmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Not Yet'), (2, 'Graduate'), (3, 'Repeat')], null=True)),
                ('training_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_status', to='students.TrainingMaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
