# Generated by Django 2.1.4 on 2019-03-07 04:25

import academy.apps.students.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_training_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.Training'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(academy.apps.students.models.get_sentinel_user), related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='batch',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='trainingstatus',
            name='training_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_status', to='students.TrainingMaterial'),
        ),
        migrations.AlterField(
            model_name='trainingstatus',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(academy.apps.students.models.get_sentinel_user), related_name='training_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
