# Generated by Django 2.1.4 on 2019-03-08 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
        ('students', '0006_auto_20190307_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='campuses.Campus'),
        ),
    ]
