# Generated by Django 2.2.6 on 2019-11-05 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingstatus',
            name='training_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_status', to='students.TrainingMaterial'),
        ),
    ]
