# Generated by Django 2.2.6 on 2020-01-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20191105_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Selection'), (5, 'Pre-Test'), (2, 'Participants'), (3, 'Repeat'), (4, 'Graduate')], default=1),
        ),
    ]
