# Generated by Django 2.2.6 on 2020-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200121_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='link_group',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
