# Generated by Django 2.1.7 on 2019-03-05 09:21

import academy.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/campuses')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=30, null=True, validators=[academy.core.validators.validate_mobile_phone])),
                ('open_registration', models.BooleanField(default=False)),
            ],
        ),
    ]
