# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='organization_name',
            new_name='specialization',
        ),
    ]
