# Generated by Django 2.1.4 on 2019-01-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='files/cv/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
