# Generated by Django 2.1.7 on 2019-07-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190105_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_via',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Web'), (2, 'Mobile')], default=1, null=True),
        ),
    ]
