# Generated by Django 2.1.7 on 2019-07-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_registered_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_valid_email',
            field=models.BooleanField(default=True),
        ),
    ]
