# Generated by Django 2.1.7 on 2019-10-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
