# Generated by Django 2.2.6 on 2019-12-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191031_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='is_html_content',
            field=models.BooleanField(default=True),
        ),
    ]
