# Generated by Django 2.2.6 on 2020-01-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_inbox_is_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
