# Generated by Django 2.2.10 on 2020-04-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200211_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_via',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Web'), (2, 'Mobile'), (3, 'Import File')], default=1, null=True),
        ),
    ]
